export enum SuperUserSceneEnums {
    "SUPER_USER_SCENE_MAIN_MENU" = "SUPER_USER_SCENE_MAIN_MENU",
    "SUPER_USER_SCENE_ADD_BOOK" = "SUPER_USER_SCENE_ADD_BOOK",
    "SUPER_USER_SCENE_ADD_BOOK_WITHOUT_COVER" = "SUPER_USER_SCENE_ADD_BOOK_WITHOUT_COVER",
    "SUPER_USER_SCENE_ADD_BOOK_WITHOUT_COVER_AGREE" = "SUPER_USER_SCENE_ADD_BOOK_WITHOUT_COVER_AGREE",
    "SUPER_USER_SCENE_ADD_BOOK_WITH_COVER" = "SUPER_USER_SCENE_ADD_BOOK_WITH_COVER",
    "SUPER_USER_SCENE_ADD_BOOK_WITH_COVER_AGREE" = "SUPER_USER_SCENE_ADD_BOOK_WITH_COVER_AGREE"
};